name: Github Action Demo   #工作流程名称
on: #定义触发actions的事件
  push:
    branches:  #启用筛选,当main分支上触发push的时候,执行工作流
      - main
jobs:
  Build:  #jobs的ID 唯一
    runs-on: ubuntu-latest  #运行的系统
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: test-vitest
        run: pnpm run test

      # - name Lint
      #   run: pnpm run lint

  # typecheck:  #jobs的ID 唯一
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #多维矩阵
  matrix_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [14.x, 16.x]
      fail-fast: false #失败处理
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
      - name: Install
        run: pnpm install

      - name: test-vitest
        run: pnpm run test